// Mocks generated by Mockito 5.3.2 from annotations
// in core/test/helpers_test/helpers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:core/core.dart' as _i4;
import 'package:core/data/models/detail_movie_model.dart' as _i3;
import 'package:core/data/models/gendres_model.dart' as _i2;
import 'package:core/data/models/movie_model.dart' as _i8;
import 'package:dartz/dartz.dart' as _i5;
import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGendreModels_0 extends _i1.SmartFake implements _i2.GendreModels {
  _FakeGendreModels_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailMovieModels_1 extends _i1.SmartFake
    implements _i3.DetailMovieModels {
  _FakeDetailMovieModels_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceApi_2 extends _i1.SmartFake implements _i4.ServiceApi {
  _FakeServiceApi_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieRemoteSource_4 extends _i1.SmartFake
    implements _i4.MovieRemoteSource {
  _FakeMovieRemoteSource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_5 extends _i1.SmartFake implements _i6.BaseOptions {
  _FakeBaseOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_6 extends _i1.SmartFake
    implements _i6.HttpClientAdapter {
  _FakeHttpClientAdapter_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_7 extends _i1.SmartFake implements _i6.Transformer {
  _FakeTransformer_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_8 extends _i1.SmartFake implements _i6.Interceptors {
  _FakeInterceptors_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_9<T> extends _i1.SmartFake implements _i6.Response<T> {
  _FakeResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceApi extends _i1.Mock implements _i4.ServiceApi {
  MockServiceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<dynamic> get({
    required String? url,
    Map<String, dynamic>? parameter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #url: url,
            #parameter: parameter,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> postData({
    required String? urlPath,
    required dynamic body,
    Map<String, dynamic>? parameter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postData,
          [],
          {
            #urlPath: urlPath,
            #body: body,
            #parameter: parameter,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> put({
    required String? urlPath,
    required dynamic body,
    Map<String, dynamic>? parameter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [],
          {
            #urlPath: urlPath,
            #body: body,
            #parameter: parameter,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> setToken(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setToken,
          [value],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
}

/// A class which mocks [MovieRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteSource extends _i1.Mock implements _i4.MovieRemoteSource {
  MockMovieRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.GendreModels> getGendres() => (super.noSuchMethod(
        Invocation.method(
          #getGendres,
          [],
        ),
        returnValue: _i7.Future<_i2.GendreModels>.value(_FakeGendreModels_0(
          this,
          Invocation.method(
            #getGendres,
            [],
          ),
        )),
      ) as _i7.Future<_i2.GendreModels>);
  @override
  _i7.Future<List<_i8.MovieModels>> getPopular() => (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.MovieModels>>.value(<_i8.MovieModels>[]),
      ) as _i7.Future<List<_i8.MovieModels>>);
  @override
  _i7.Future<_i3.DetailMovieModels> detailById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #detailById,
          [],
          {#id: id},
        ),
        returnValue:
            _i7.Future<_i3.DetailMovieModels>.value(_FakeDetailMovieModels_1(
          this,
          Invocation.method(
            #detailById,
            [],
            {#id: id},
          ),
        )),
      ) as _i7.Future<_i3.DetailMovieModels>);
}

/// A class which mocks [MovieRemoteSourceImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteSourceImplementation extends _i1.Mock
    implements _i4.MovieRemoteSourceImplementation {
  MockMovieRemoteSourceImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ServiceApi get serviceApi => (super.noSuchMethod(
        Invocation.getter(#serviceApi),
        returnValue: _FakeServiceApi_2(
          this,
          Invocation.getter(#serviceApi),
        ),
      ) as _i4.ServiceApi);
  @override
  _i7.Future<_i2.GendreModels> getGendres() => (super.noSuchMethod(
        Invocation.method(
          #getGendres,
          [],
        ),
        returnValue: _i7.Future<_i2.GendreModels>.value(_FakeGendreModels_0(
          this,
          Invocation.method(
            #getGendres,
            [],
          ),
        )),
      ) as _i7.Future<_i2.GendreModels>);
  @override
  _i7.Future<_i3.DetailMovieModels> detailById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #detailById,
          [],
          {#id: id},
        ),
        returnValue:
            _i7.Future<_i3.DetailMovieModels>.value(_FakeDetailMovieModels_1(
          this,
          Invocation.method(
            #detailById,
            [],
            {#id: id},
          ),
        )),
      ) as _i7.Future<_i3.DetailMovieModels>);
  @override
  _i7.Future<List<_i8.MovieModels>> getPopular() => (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.MovieModels>>.value(<_i8.MovieModels>[]),
      ) as _i7.Future<List<_i8.MovieModels>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i4.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>> getGendres() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGendres,
          [],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>>.value(
                _FakeEither_3<_i4.Failure, _i2.GendreModels>(
          this,
          Invocation.method(
            #getGendres,
            [],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>>);
  @override
  _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>> getPopular() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>>.value(
                _FakeEither_3<_i4.Failure, List<_i8.MovieModels>>(
          this,
          Invocation.method(
            #getPopular,
            [],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>>);
  @override
  _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>> dataMovieById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #dataMovieById,
          [id],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>>.value(
                _FakeEither_3<_i4.Failure, _i3.DetailMovieModels>(
          this,
          Invocation.method(
            #dataMovieById,
            [id],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>>);
}

/// A class which mocks [MovieRepositoryImplementation].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepositoryImplementation extends _i1.Mock
    implements _i4.MovieRepositoryImplementation {
  MockMovieRepositoryImplementation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRemoteSource get movieRemoteSource => (super.noSuchMethod(
        Invocation.getter(#movieRemoteSource),
        returnValue: _FakeMovieRemoteSource_4(
          this,
          Invocation.getter(#movieRemoteSource),
        ),
      ) as _i4.MovieRemoteSource);
  @override
  _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>> getGendres() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGendres,
          [],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>>.value(
                _FakeEither_3<_i4.Failure, _i2.GendreModels>(
          this,
          Invocation.method(
            #getGendres,
            [],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, _i2.GendreModels>>);
  @override
  _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>> dataMovieById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #dataMovieById,
          [id],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>>.value(
                _FakeEither_3<_i4.Failure, _i3.DetailMovieModels>(
          this,
          Invocation.method(
            #dataMovieById,
            [id],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, _i3.DetailMovieModels>>);
  @override
  _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>> getPopular() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopular,
          [],
        ),
        returnValue:
            _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>>.value(
                _FakeEither_3<_i4.Failure, List<_i8.MovieModels>>(
          this,
          Invocation.method(
            #getPopular,
            [],
          ),
        )),
      ) as _i7.Future<_i5.Either<_i4.Failure, List<_i8.MovieModels>>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i6.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_5(
          this,
          Invocation.getter(#options),
        ),
      ) as _i6.BaseOptions);
  @override
  set options(_i6.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_6(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i6.HttpClientAdapter);
  @override
  set httpClientAdapter(_i6.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_7(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i6.Transformer);
  @override
  set transformer(_i6.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_8(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i6.Interceptors);
  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i6.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> head<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  void lock() => super.noSuchMethod(
        Invocation.method(
          #lock,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void unlock() => super.noSuchMethod(
        Invocation.method(
          #unlock,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i6.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i6.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i6.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i7.Future<_i6.Response<dynamic>>.value(_FakeResponse_9<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<dynamic>>);
  @override
  _i7.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i6.ProgressCallback? onReceiveProgress,
    _i6.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i6.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i7.Future<_i6.Response<dynamic>>.value(_FakeResponse_9<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<dynamic>>);
  @override
  _i7.Future<_i6.Response<T>> request<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i6.CancelToken? cancelToken,
    _i6.Options? options,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #request,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    dynamic data,
    _i6.CancelToken? cancelToken,
    _i6.Options? options,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
  @override
  _i7.Future<_i6.Response<T>> fetch<T>(_i6.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i7.Future<_i6.Response<T>>.value(_FakeResponse_9<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i7.Future<_i6.Response<T>>);
}
